profile-name: "local"

server:
  port: 8080

spring:
  application:
    name: multi-module
  datasource:
    url: jdbc:mysql://localhost:3306/multimodule_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: woojoo
    password: Woojoo0425@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create # or `none`
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Tokyo # @CreatedDate 필드의 Time Zone 값 설정