# Docker Compose의 버전 정보
version: '3.8'

services:
  mysql: # 서비스의 이름
    container_name: multimodule_local
    image: mysql:latest
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment: # 환경 변수
      - MYSQL_DATABASE=multimodule_local
      - MYSQL_USER=woojoo
      - MYSQL_PASSWORD=Woojoo0425@
      - MYSQL_ROOT_PASSWORD=Woojoo0425
      - TZ=Asia/Tokyo